name = "StaticUnivariatePolynomials"
uuid = "acf665a8-1387-11e9-3699-7f83672d90f1"
authors = ["Twan Koolen <koolen.twan@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
